// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6fk5Nej9vibqeWYJg2dw_VSFFtzUXjI',
    appId: '1:370493672051:web:5e0b72cfa09989e9e9b806',
    messagingSenderId: '370493672051',
    projectId: 'hichat-5b37b',
    authDomain: 'hichat-5b37b.firebaseapp.com',
    storageBucket: 'hichat-5b37b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQChrKGibu3uXs3EqWLLIFlH8j_uElO4',
    appId: '1:370493672051:android:041fbecf98814cfee9b806',
    messagingSenderId: '370493672051',
    projectId: 'hichat-5b37b',
    storageBucket: 'hichat-5b37b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxGfWnoATKitgkvgdxQjp_1sa6MNi5mI',
    appId: '1:370493672051:ios:91a9226ab677c87ce9b806',
    messagingSenderId: '370493672051',
    projectId: 'hichat-5b37b',
    storageBucket: 'hichat-5b37b.firebasestorage.app',
    iosBundleId: 'com.example.hiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxGfWnoATKitgkvgdxQjp_1sa6MNi5mI',
    appId: '1:370493672051:ios:91a9226ab677c87ce9b806',
    messagingSenderId: '370493672051',
    projectId: 'hichat-5b37b',
    storageBucket: 'hichat-5b37b.firebasestorage.app',
    iosBundleId: 'com.example.hiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ6fk5Nej9vibqeWYJg2dw_VSFFtzUXjI',
    appId: '1:370493672051:web:68568fdebac3076fe9b806',
    messagingSenderId: '370493672051',
    projectId: 'hichat-5b37b',
    authDomain: 'hichat-5b37b.firebaseapp.com',
    storageBucket: 'hichat-5b37b.firebasestorage.app',
  );
}
